name: coord_bot
on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  tweet-tweet:
    runs-on: macos-latest
    env:
      COORD_BOT_TWITTER_CONSUMER_API_KEY: ${{ secrets.COORD_BOT_TWITTER_CONSUMER_API_KEY }}
      COORD_BOT_TWITTER_CONSUMER_API_SECRET: ${{ secrets.COORD_BOT_TWITTER_CONSUMER_API_SECRET }}
      COORD_BOT_TWITTER_ACCESS_TOKEN: ${{ secrets.COORD_BOT_TWITTER_ACCESS_TOKEN }}
      COORD_BOT_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.COORD_BOT_TWITTER_ACCESS_TOKEN_SECRET }}
      MAPQUEST_API_TOKEN: ${{ secrets.MAPQUEST_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet & rjson packages
        run: Rscript -e 'install.packages(c("rtweet", "rjson"), dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript coord_bot.R
        
